name: Weekly Sleeper Report

on:
  workflow_dispatch:
    inputs:
      week:
        description: "NFL Woche (leer = aktuelle Woche)"
        required: false
  schedule:
    - cron: "30 6 * * 2"  # dienstags 06:30 UTC ~ dienstags morgens CET/CET

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run weekly report
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLEEPER_LEAGUE_ID: ${{ secrets.SLEEPER_LEAGUE_ID }}
          WEEK: ${{ github.event.inputs.week }}
          LANGUAGE: de
          TONE: witzig
          OUTPUT_DIR: reports
        run: npm run weekly:report

      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add reports/
            git commit -m "Weekly report (auto)"
            git push
          else
            echo "No changes to commit"
          fi
